export interface SettingJson {
  id: string | null;
  minimum_deposit: string | null;
  minimum_withdrawal: string | null;
  bonus_percent: string | null;
  moov_password: string | null;
  mtn_password: string | null;
  sbin_password: string | null;
  card_password: string | null;
  mtn_url: string | null;
  moov_url: string | null;
  card_url: string | null;
  sbin_url: string | null;
  hash: string | null;
  cash_desk_id: string | null;
  cashierpass: string | null;
  moov_customer: string | null;
  mtn_customer: string | null;
  card_customer: string | null;
  sbin_customer: string | null;
}

export interface SettingFormData {
  id?: string | undefined;
  minimumDeposit: string | null;
  minimumWithdrawal: string | null;
  bonusPercent: string | null;
  moovPassword: string | null;
  mtnPassword: string | null;
  sbinPassword: string | null;
  cardPassword: string | null;
  mtnUrl: string | null;
  moovUrl: string | null;
  cardUrl: string | null;
  sbinUrl: string | null;
  hash: string | null;
  cashDeskId: string | null;
  cashierPass: string | null;
  moovCustomer: string | null;
  mtnCustomer: string | null;
  cardCustomer: string | null;
  sbinCustomer: string | null;
}

export interface SettingFormErrors {
  minimumDeposit: string | null;
  minimumWithdrawal: string | null;
  bonusPercent: string | null;
  moovPassword: string | null;
  mtnPassword: string | null;
  sbinPassword: string | null;
  cardPassword: string | null;
  mtnUrl: string | null;
  moovUrl: string | null;
  cardUrl: string | null;
  sbinUrl: string | null;
  hash: string | null;
  cashDeskId: string | null;
  cashierPass: string | null;
  moovCustomer: string | null;
  mtnCustomer: string | null;
  cardCustomer: string | null;
  sbinCustomer: string | null;
}
